name: workflow
run-name: CI/CD
on:
  push:
    branches: '*'
jobs:
  codequality:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -ex
          git config --global --add safe.directory $GITHUB_WORKSPACE
          python3 -m pip install uv
          uv sync
          uv run pre-commit run --all-files
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container: python:3.12
    environment: release
    needs: codequality
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          set -ex
          python3 -m pip install uv
          uv sync
          uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@0a87186d5f9e2303ed3c19e0fdd59abe52a28bb7
